stages:
  - test
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: always

variables:
  PYTHON_VERSION: 3.8.10

test-angular-app-build:
  stage: test
  image: node:16.10.0
  rules:
    - when: on_success
  before_script:
    - npm install -g @angular/cli
    - cd frontend
    - npm ci
  script:
    - node node_modules/@angular/cli/bin/ng build --configuration production
  #  artifacts:
  #    expire_in: 7 day
  #    paths:
  #      - dist/
  tags:
    - container


unit_tests:
  stage: test
  image: python:$PYTHON_VERSION
  before_script:
    - pip install pytest
    - git config --global credential.https://gitlab.fit.fraunhofer.de/daniel.schuster/interactive_process_mining_core.git.username ${cortado_core_git_username}
    - git config --global credential.https://gitlab.fit.fraunhofer.de/pm4py/pm4py-core.git.username ${pm4py_core_git_username}
    - git config --global credential.helper store
    - git config --global credential.interactive never
    - echo https://${cortado_core_git_username}:${cortado_core_git_password}@gitlab.fit.fraunhofer.de >> /root/.git-credentials
    - echo https://${pm4py_core_git_username}:${pm4py_core_git_password}@gitlab.fit.fraunhofer.de >> /root/.git-credentials
    - pip install -r backend/requirements.txt
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 2 weeks

    
build-electron-app-windows:
  stage: build
  image: electronuserland/builder:wine
  rules:
    - when: on_success
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run build-prod
    - npm run build-electron-only-windows
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - frontend/app-dist/win-unpacked
    expire_in: 1 week

build-electron-app-linux:
  stage: build
  image: electronuserland/builder
  rules:
    - when: on_success
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run build-prod
    - npm run build-electron-only-linux
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - frontend/app-dist/linux-unpacked
    expire_in: 1 week
