stages:
  - lint
  - test
  - build-backend
  - build-frontend

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: always

variables:
  PYINSTALLER_VERSION: "4.3"
  PYTHON_VERSION: "3.8.10"
  ARTIFACT_NAME_SUFFIX: $CI_COMMIT_SHA-$CI_COMMIT_TIMESTAMP
  LINUX_BACKEND_ARTIFACT_NAME: Cortado_Linux_backend_$ARTIFACT_NAME_SUFFIX
  WINDOWS_BACKEND_ARTIFACT_NAME: Cortado_Windows_backend_$ARTIFACT_NAME_SUFFIX
  LINUX_BUILD_DIR: Cortado_Linux_build_$ARTIFACT_NAME_SUFFIX
  WINDOWS_BUILD_DIR: Cortado_Windows_build_$ARTIFACT_NAME_SUFFIX

eslint-check:
  stage: lint
  image: node
  rules:
    - when: on_success
  before_script:
    - cd frontend
    - npm ci
  script:
    - ./node_modules/.bin/eslint src/
  
test-angular-app-build:
  stage: test
  image: node:16.10.0
  rules:
    - when: on_success
  before_script:
    - npm install -g @angular/cli
    - cd frontend
    - npm ci
  script:
    - node node_modules/@angular/cli/bin/ng build --configuration production
  # artifacts:
  #   expire_in: 7 day
  #   paths:
  #     - dist/
  tags:
    - container

# build-backend-windows is coming soon 

unit_tests:
  stage: test
  image: python:$PYTHON_VERSION
  before_script:
    - pip install pytest
    - git config --global credential.https://gitlab.fit.fraunhofer.de/daniel.schuster/interactive_process_mining_core.git.username ${cortado_core_git_username}
    - git config --global credential.https://gitlab.fit.fraunhofer.de/pm4py/pm4py-core.git.username ${pm4py_core_git_username}
    - git config --global credential.helper store
    - git config --global credential.interactive never
    - echo https://${cortado_core_git_username}:${cortado_core_git_password}@gitlab.fit.fraunhofer.de >> /root/.git-credentials
    - echo https://${pm4py_core_git_username}:${pm4py_core_git_password}@gitlab.fit.fraunhofer.de >> /root/.git-credentials
    - pip install -r backend/requirements.txt
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 2 weeks

build-backend-linux:
  stage: build-backend
  image: python:$PYTHON_VERSION
  rules:
    - when: on_success
  before_script:
    - echo "machine gitlab.fit.fraunhofer.de login gitlab-ci-token password $CI_JOB_TOKEN" > ~/.netrc 
    - cd backend
    - pip install -r requirements.txt
    # - pip install graphviz==0.17
    - pip install pyinstaller==$PYINSTALLER_VERSION
  script:
    - pyinstaller --noconfirm --clean cortado-backend.spec
    - cd ..
    - cp -R backend/dist/cortado-backend .
  artifacts:
    name: $LINUX_BACKEND_ARTIFACT_NAME
    paths:
      - cortado-backend
    expire_in: 1 week
    
build-electron-app-windows:
  stage: build-frontend
  image: electronuserland/builder:wine
  rules:
    - when: on_success
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run build-prod
    - npm run build-electron-only-windows
    - cd ..
    - mkdir $WINDOWS_BUILD_DIR
    - cp -R frontend/app-dist/win-unpacked/* $WINDOWS_BUILD_DIR
    # - cp -R cortado-backend $WINDOWS_BUILD_DIR
  artifacts:
    name: $WINDOWS_BUILD_DIR
    paths:
      - $WINDOWS_BUILD_DIR
    expire_in: 1 week

build-electron-app-linux:
  stage: build-frontend
  image: electronuserland/builder
  rules:
    - when: on_success
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run build-prod
    - npm run build-electron-only-linux
    - cd ..
    - mkdir $LINUX_BUILD_DIR
    - cp -R frontend/app-dist/linux-unpacked/* $LINUX_BUILD_DIR
    - cp -R cortado-backend $LINUX_BUILD_DIR
  dependencies:
    - build-backend-linux
  artifacts:
    name: ${LINUX_BUILD_DIR//:}
    paths:
      - $LINUX_BUILD_DIR
    expire_in: 1 week
