export const test = {
  "number_ancestor_cases": 20,
  "number_ancestor_events": 1394,
  "number_ancestor_variants": 20,
  "number_self_cases": 20,
  "number_self_events": 1394,
  "number_self_variants": 20,
  "variants": [{
    "caseDuration": 1320.0,
    "count": 1,
    "variant": "Ultrasound configuration+start,Ultrasound configuration+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Cover probe+start,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Puncture+start,Puncture+complete,Puncture+start,Puncture+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Puncture+start,Puncture+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Check wire in long axis+start,Check wire in long axis+complete,Check wire in long axis+start,Guidewire install+complete,Check wire in long axis+complete,Wire in good position+start,Wire in good position+complete,Check wire in long axis+start,Check wire in long axis+complete,Remove trocar+start,Remove trocar+complete,Advance catheter+start,Advance catheter+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 5520.0,
    "count": 1,
    "variant": "Prepare implements+start,Prepare implements+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Position patient+start,Position patient+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Prepare implements+start,Prepare implements+complete,Anesthetize+start,Anesthetize+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Gel in probe+start,Gel in probe+complete,Cover probe+start,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Prepare implements+start,Prepare implements+complete,Anesthetize+start,Anesthetize+complete,Prepare implements+start,Prepare implements+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Anatomic identification+start,Anatomic identification+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Doppler identification+start,Doppler identification+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Position probe+start,Position probe+complete,Anatomic identification+start,Anatomic identification+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete"
  }, {
    "caseDuration": 1020.0,
    "count": 1,
    "variant": "Prepare implements+start,Prepare implements+complete,Ultrasound configuration+start,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Ultrasound configuration+complete,Doppler identification+start,Doppler identification+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Gel in probe+start,Gel in probe+complete,Cover probe+start,Cover probe+complete,Prepare implements+start,Prepare implements+complete,Put sterile gel+start,Put sterile gel+complete,Anesthetize+start,Anesthetize+complete,Prepare implements+start,Prepare implements+complete,Position probe+start,Position probe+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Wire in good position+start,Wire in good position+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Check wire in long axis+start,Check wire in long axis+complete,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 1620.0,
    "count": 1,
    "variant": "Prepare implements+start,Prepare implements+complete,Position patient+start,Position patient+complete,Hand washing+start,Hand washing+complete,Prepare implements+start,Prepare implements+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Clean puncture area+start,Clean puncture area+complete,Prepare implements+start,Prepare implements+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Anesthetize+start,Anesthetize+complete,Cover probe+start,Gel in probe+start,Gel in probe+complete,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Anatomic identification+start,Anatomic identification+complete,Ultrasound configuration+start,Compression identification+start,Compression identification+complete,Ultrasound configuration+complete,Put sterile gel+start,Put sterile gel+complete,Prepare implements+start,Prepare implements+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Blood return+start,Blood return+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Remove trocar+start,Remove trocar+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete"
  }, {
    "caseDuration": 87300.0,
    "count": 1,
    "variant": "Prepare implements+start,Prepare implements+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Gel in probe+start,Gel in probe+complete,Cover probe+start,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Doppler identification+start,Doppler identification+complete,Anesthetize+start,Anesthetize+complete,Prepare implements+start,Prepare implements+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Wire in good position+start,Wire in good position+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 1260.0,
    "count": 1,
    "variant": "Prepare implements+start,Prepare implements+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Prepare implements+start,Prepare implements+complete,Get in sterile clothes+start,Hand washing+start,Hand washing+complete,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Prepare implements+start,Prepare implements+complete,Drap puncture area+start,Drap puncture area+complete,Cover probe+start,Cover probe+complete,Gel in probe+start,Gel in probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Anatomic identification+start,Anatomic identification+complete,Anesthetize+start,Anesthetize+complete,Compression identification+start,Compression identification+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Compression identification+start,Compression identification+complete,Anatomic identification+start,Anatomic identification+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check catheter position+start,Check catheter position+complete,Check flow and reflow+start,Check flow and reflow+complete"
  }, {
    "caseDuration": 5640.0,
    "count": 1,
    "variant": "Prepare implements+start,Prepare implements+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Gel in probe+start,Gel in probe+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Cover probe+start,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Prepare implements+start,Prepare implements+complete,Position probe+start,Position probe+complete,Anesthetize+start,Anesthetize+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Guidewire install+start,Guidewire install+complete,Position probe+start,Position probe+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Wire in good position+start,Wire in good position+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Remove guidewire+start,Remove guidewire+complete,Position probe+start,Position probe+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Remove trocar+start,Remove trocar+complete,Check wire in long axis+start,Check wire in long axis+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Advance catheter+start,Advance catheter+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete"
  }, {
    "caseDuration": 780.0,
    "count": 1,
    "variant": "Prepare implements+start,Prepare implements+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Gel in probe+start,Gel in probe+complete,Cover probe+start,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Anatomic identification+start,Anatomic identification+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Compression identification+start,Compression identification+complete,Prepare implements+start,Prepare implements+complete,Anesthetize+start,Anesthetize+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Wire in good position+start,Wire in good position+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 1080.0,
    "count": 1,
    "variant": "Prepare implements+start,Prepare implements+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Cover probe+start,Gel in probe+start,Gel in probe+complete,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Anesthetize+start,Anesthetize+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Wire in good position+start,Wire in good position+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 660.0,
    "count": 1,
    "variant": "Prepare implements+start,Prepare implements+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Gel in probe+start,Gel in probe+complete,Cover probe+start,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Compression identification+start,Compression identification+complete,Anatomic identification+start,Anatomic identification+complete,Anesthetize+start,Anesthetize+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in long axis+start,Check wire in long axis+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 780.0,
    "count": 1,
    "variant": "Prepare implements+start,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Gel in probe+start,Gel in probe+complete,Cover probe+start,Cover probe+complete,Prepare implements+start,Prepare implements+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Compression identification+start,Compression identification+complete,Anesthetize+start,Anesthetize+complete,Prepare implements+start,Prepare implements+complete,Position patient+start,Position patient+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Wire in good position+start,Wire in good position+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 960.0,
    "count": 1,
    "variant": "Position patient+start,Position patient+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Gel in probe+start,Gel in probe+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Cover probe+start,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Prepare implements+start,Prepare implements+complete,Anesthetize+start,Anesthetize+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 1320.0,
    "count": 1,
    "variant": "Hand washing+start,Hand washing+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Gel in probe+start,Gel in probe+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Cover probe+start,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Anatomic identification+start,Anatomic identification+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Prepare implements+start,Prepare implements+complete,Anesthetize+start,Anesthetize+complete,Anatomic identification+start,Anatomic identification+complete,Puncture+start,Ultrasound configuration+start,Ultrasound configuration+complete,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 960.0,
    "count": 1,
    "variant": "Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Anatomic identification+start,Anatomic identification+complete,Gel in probe+start,Gel in probe+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Cover probe+start,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Prepare implements+start,Prepare implements+complete,Position probe+start,Position probe+complete,Anesthetize+start,Anesthetize+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Wire in good position+start,Wire in good position+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 960.0,
    "count": 1,
    "variant": "Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Cover probe+start,Gel in probe+start,Gel in probe+complete,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Compression identification+start,Compression identification+complete,Doppler identification+start,Doppler identification+complete,Anatomic identification+start,Anatomic identification+complete,Anesthetize+start,Anesthetize+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Wire in good position+start,Wire in good position+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 1260.0,
    "count": 1,
    "variant": "Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Position patient+start,Position patient+complete,Prepare implements+start,Prepare implements+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Cover probe+start,Ultrasound configuration+start,Ultrasound configuration+complete,Gel in probe+start,Gel in probe+complete,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Anesthetize+start,Anesthetize+complete,Position probe+start,Position probe+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 4560.0,
    "count": 1,
    "variant": "Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Prepare implements+start,Prepare implements+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Cover probe+start,Gel in probe+start,Gel in probe+complete,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Prepare implements+start,Prepare implements+complete,Ultrasound configuration+start,Position probe+start,Position probe+complete,Anatomic identification+start,Anatomic identification+complete,Ultrasound configuration+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Compression identification+start,Compression identification+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Remove trocar+start,Remove trocar+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 1500.0,
    "count": 1,
    "variant": "Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Position patient+start,Position patient+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Prepare implements+start,Prepare implements+complete,Gel in probe+start,Gel in probe+complete,Cover probe+start,Cover probe+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Anesthetize+start,Anesthetize+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Check wire in short axis+start,Check wire in short axis+complete,Wire in good position+start,Wire in good position+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Advance catheter+start,Advance catheter+complete,Advance catheter+start,Advance catheter+complete,Advance catheter+start,Advance catheter+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Advance catheter+start,Advance catheter+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 1380.0,
    "count": 1,
    "variant": "Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Gel in probe+start,Gel in probe+complete,Cover probe+start,Cover probe+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Anatomic identification+start,Anatomic identification+complete,Compression identification+start,Compression identification+complete,Doppler identification+start,Doppler identification+complete,Anesthetize+start,Anesthetize+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Guidewire install+start,Guidewire install+complete,Remove trocar+start,Remove trocar+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }, {
    "caseDuration": 4920.0,
    "count": 1,
    "variant": "Get in sterile clothes+start,Get in sterile clothes+complete,Hand washing+start,Hand washing+complete,Get in sterile clothes+start,Get in sterile clothes+complete,Clean puncture area+start,Clean puncture area+complete,Drap puncture area+start,Drap puncture area+complete,Prepare implements+start,Prepare implements+complete,Cover probe+start,Gel in probe+start,Gel in probe+complete,Cover probe+complete,Prepare implements+start,Prepare implements+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Put sterile gel+start,Put sterile gel+complete,Position probe+start,Position probe+complete,Anatomic identification+start,Anatomic identification+complete,Ultrasound configuration+start,Ultrasound configuration+complete,Compression identification+start,Compression identification+complete,Prepare implements+start,Prepare implements+complete,Position probe+start,Position probe+complete,Anesthetize+start,Anesthetize+complete,Puncture+start,Puncture+complete,Blood return+start,Blood return+complete,Drop probe+start,Drop probe+complete,Remove syringe+start,Remove syringe+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Guidewire install+start,Guidewire install+complete,Blood return+start,Blood return+complete,Guidewire install+start,Guidewire install+complete,Check wire in short axis+start,Check wire in short axis+complete,Remove trocar+start,Remove trocar+complete,Check wire in short axis+start,Check wire in short axis+complete,Check wire in long axis+start,Check wire in long axis+complete,Widen pathway+start,Widen pathway+complete,Advance catheter+start,Advance catheter+complete,Remove guidewire+start,Remove guidewire+complete,Check flow and reflow+start,Check flow and reflow+complete,Check catheter position+start,Check catheter position+complete"
  }]
}
